<script lang="ts">
	import type { Component } from 'svelte';

	/**
	 * Renders either an SVG string or Svelte component icon inside a stable tree icon slot.
	 */
	type Props = {
		icon: string | Component;
	};

	const { icon }: Props = $props();
</script>

<span class="icon-slot">
	{#if typeof icon === 'string'}
		<!-- eslint-disable-next-line svelte/no-at-html-tags -- Node icons are generated by trusted local icon helpers. -->
		{@html icon}
	{:else}
		{@const Icon = icon}
		<Icon />
	{/if}
</span>
